# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-06-20 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympicanalysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medaltable',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
